FROM php:5.6-fpm

ARG PHP_PORT
ARG HOST_UID

RUN usermod -u $HOST_UID www-data

RUN apt-get update \
  && apt-get install -y gettext \
    libmcrypt-dev \
    libjpeg62-turbo-dev \
    libpcre3-dev \
    libpng-dev \
    libfreetype6-dev \
    libxml2-dev \
    libicu-dev \
    mysql-client \
    wget \
    unzip \
    git \
  && rm -rf /var/lib/apt/lists/* \ && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install iconv intl pdo pdo_mysql mbstring soap gd zip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer --version

COPY php.ini /usr/local/etc/php
COPY www.conf.template /usr/local/etc/php-fpm.d/www.conf.template

RUN envsubst '$PHP_PORT $HOST_UID' < /usr/local/etc/php-fpm.d/www.conf.template > /usr/local/etc/php-fpm.d/www.conf

RUN docker-php-ext-install mysql
RUN docker-php-ext-install mcrypt
RUN docker-php-ext-install opcache

# install composer
COPY install-composer.sh /tmp/install-composer.sh
RUN chmod +x /tmp/install-composer.sh
RUN bash /tmp/install-composer.sh
VOLUME /root/.composer

WORKDIR /var/www/html
